version: '3.8'

services:
  db:
    image: mariadb:10.9
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=multifaucet
      - MYSQL_DATABASE=multifaucet
      - MYSQL_USER=multifaucet
      - MYSQL_PASSWORD=multifaucet
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql:/var/lib/mysql

  multifaucet:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./config/faucet:/var/www/html/config:ro
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql:
